// Generated by tools\probe_se_api_surface.ps1
// Source Bin64: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
namespace Sandbox.ModAPI.Ingame
{
    public enum BroadcastTarget
    {
        Owner,
        Faction,
        Everyone
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum ChargeMode
    {
        Auto,
        Recharge,
        Discharge
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum DoorStatus
    {
        Opening,
        Open,
        Closing,
        Closed
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum FlightMode
    {
        Patrol,
        Circle,
        OneWay,
        Track,
        WorkArea
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAdvancedDoor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAirtightDoorBase
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAirtightHangarDoor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAirtightSlideDoor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAssembler
    {
        bool CooperativeMode { get; set; }
        float CurrentProgress { get; }
        bool DisassembleEnabled { get; }
        Sandbox.ModAPI.Ingame.MyAssemblerMode Mode { get; set; }
        bool Repeating { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAttachableTopBlock
    {
        Sandbox.ModAPI.Ingame.IMyMechanicalConnectionBlock Base { get; }
        bool IsAttached { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAttackPatternComponent
    {
        long AttackPatternId { get; }
        VRage.Utils.MyStringId AttackPatternName { get; }
        VRage.Utils.MyStringId AttackPatternTooltip { get; }
        bool HasEnemy { get; }
        bool IsSelected { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyAutopilotWaypoint
    {
        VRageMath.MatrixD Matrix { get; }
        string Name { get; }
        long RelatedEntityId { get; }
        VRageMath.MatrixD RelativeMatrix { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBasicMissionBlock
    {
        long SelectedMissionId { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBasicMissionComponent
    {
        System.Text.StringBuilder DetailedInfo { get; }
        bool IsSelected { get; set; }
        VRage.Utils.MyStringId MissionName { get; }
        long UniqueSelectionId { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBasicMissionFollowHome
    {
        float MaxRange { get; set; }
        float MinRange { get; set; }
        bool Wander { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBasicMissionFollowPlayer
    {
        float FollowDistance { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBatteryBlock
    {
        Sandbox.ModAPI.Ingame.ChargeMode ChargeMode { get; set; }
        float CurrentInput { get; }
        float CurrentStoredPower { get; }
        bool HasCapacityRemaining { get; }
        bool IsCharging { get; }
        float MaxInput { get; }
        float MaxStoredPower { get; }
        bool OnlyDischarge { get; set; }
        bool OnlyRecharge { get; set; }
        bool SemiautoEnabled { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBeacon
    {
        string HudText { get; set; }
        float Radius { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBlockGroup
    {
        string Name { get; }
        void GetBlocks(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyTerminalBlock> blocks, System.Func`<Sandbox.ModAPI.Ingame.IMyTerminalBlock, bool> collect);
        void GetBlocksOfType(<> blocks, <, bool> collect);
        void GetBlocksOfType(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyTerminalBlock> blocks, System.Func`<Sandbox.ModAPI.Ingame.IMyTerminalBlock, bool> collect);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBroadcastControllerBlock
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyBroadcastListener
    {
        bool IsActive { get; }
        string Tag { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCameraBlock
    {
        double AvailableScanRange { get; }
        bool EnableRaycast { get; set; }
        bool IsActive { get; }
        float RaycastConeLimit { get; }
        double RaycastDistanceLimit { get; }
        float RaycastTimeMultiplier { get; }
        bool CanScan(double distance, VRageMath.Vector3D direction);
        bool CanScan(VRageMath.Vector3D target);
        bool CanScan(double distance);
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo Raycast(double distance, float pitch, float yaw);
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo Raycast(VRageMath.Vector3D targetPos);
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo Raycast(double distance, VRageMath.Vector3D targetDirection);
        int TimeUntilScan(double distance);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCargoContainer
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCharacterAimAssistComponent
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyChatBroadcastControllerComponent
    {
        Sandbox.ModAPI.Ingame.BroadcastTarget BroadcastTarget { get; set; }
        string CustomName { get; set; }
        int MaxMessageCount { get; }
        bool UseAntenna { get; set; }
        string GetMessage(int messageIndex);
        void SendGps();
        void SendMessage(string message);
        void SendMessage(int messageIndex);
        void SendRandomMessage();
        void SetMessage(int messageIndex, string message);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCockpit
    {
        float OxygenCapacity { get; }
        float OxygenFilledRatio { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCollector
    {
        bool UseConveyorSystem { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyConveyor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyConveyorSorter
    {
        bool DrainAll { get; set; }
        Sandbox.ModAPI.Ingame.MyConveyorSorterMode Mode { get; }
        void AddItem(Sandbox.ModAPI.Ingame.MyInventoryItemFilter item);
        void GetFilterList(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyInventoryItemFilter> items);
        bool IsAllowed(VRage.Game.MyDefinitionId id);
        void RemoveItem(Sandbox.ModAPI.Ingame.MyInventoryItemFilter item);
        void SetFilter(Sandbox.ModAPI.Ingame.MyConveyorSorterMode mode, System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyInventoryItemFilter> items);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyConveyorTube
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyCryoChamber
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyDecoy
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyDefensiveCombatBlock
    {
        System.Nullable`<VRageMath.Vector3D> CustomFleeCoordinates { get; set; }
        System.Nullable`<long> FleeBeaconEntityId { get; }
        System.Nullable`<VRageMath.Vector3D> FleeCoordinates { get; }
        System.Nullable`<VRage.Game.ObjectBuilders.AI.GpsInfo> FleeGps { get; }
        VRage.Game.ModAPI.Ingame.FleeTrigger FleeTrigger { get; set; }
        bool IsFleeing { get; }
        bool LockTarget { get; set; }
        Sandbox.ModAPI.Ingame.IMySearchEnemyComponent SearchEnemyComponent { get; }
        float WaypointZoneSize { get; set; }
        void Flee();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyDoor
    {
        bool Open { get; }
        float OpenRatio { get; }
        Sandbox.ModAPI.Ingame.DoorStatus Status { get; }
        void CloseDoor();
        void OpenDoor();
        void ToggleDoor();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyEmotionControllerBlock
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyEventControllerBlock
    {
        bool IsAndModeEnabled { get; set; }
        bool IsLowerOrEqualCondition { get; set; }
        float Threshold { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyExtendedPistonBase
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyFarmPlotLogic
    {
        int AmountOfSeedsRequired { get; }
        bool IsAlive { get; }
        bool IsHarvestable { get; }
        bool IsPlantFullyGrown { get; }
        bool IsPlantPlanted { get; }
        VRage.Game.MyDefinitionId OutputItem { get; }
        int OutputItemAmount { get; }
        string GetDetailedInfoWithoutRequiredInput();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyFlightMovementBlock
    {
        bool AlignToPGravity { get; set; }
        bool CollisionAvoidance { get; set; }
        Sandbox.ModAPI.Ingame.IMyAutopilotWaypoint CurrentWaypoint { get; }
        Sandbox.ModAPI.Ingame.FlightMode FlightMode { get; set; }
        bool IsAutoPilotEnabled { get; }
        System.Nullable`<VRageMath.Vector3D> LookAtPosition { get; set; }
        float MinimalAltitude { get; set; }
        bool PrecisionMode { get; set; }
        float SpeedLimit { get; set; }
        void GetWaypoints(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyAutopilotWaypoint> points);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyFunctionalBlock
    {
        bool Enabled { get; set; }
        void RequestEnable(bool enable);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGasGenerator
    {
        bool AutoRefill { get; set; }
        bool IsProducing { get; }
        bool UseConveyorSystem { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGasTank
    {
        bool AutoRefillBottles { get; set; }
        float Capacity { get; }
        double FilledRatio { get; }
        bool Stockpile { get; set; }
        void RefillBottles();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGridProgramRuntimeInfo
    {
        int CurrentCallChainDepth { get; }
        int CurrentInstructionCount { get; }
        double LastRunTimeMs { get; }
        long LifetimeTicks { get; }
        int MaxCallChainDepth { get; }
        int MaxInstructionCount { get; }
        System.TimeSpan TimeSinceLastRun { get; }
        Sandbox.ModAPI.Ingame.UpdateFrequency UpdateFrequency { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGridProgramWorldInfo
    {
        float InventoryMultiplier { get; }
        float LargeShipMaxAngularSpeed { get; }
        float LargeShipMaxSpeed { get; }
        bool PressurizationEnabled { get; }
        float SmallShipMaxAngularSpeed { get; }
        float SmallShipMaxSpeed { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGridTerminalSystem
    {
        bool CanAccess(Sandbox.ModAPI.Ingame.IMyTerminalBlock block, Sandbox.ModAPI.Ingame.MyTerminalAccessScope scope);
        bool CanAccess(VRage.Game.ModAPI.Ingame.IMyCubeGrid grid, Sandbox.ModAPI.Ingame.MyTerminalAccessScope scope);
        void GetBlockGroups(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyBlockGroup> blockGroups, System.Func`<Sandbox.ModAPI.Ingame.IMyBlockGroup, bool> collect);
        Sandbox.ModAPI.Ingame.IMyBlockGroup GetBlockGroupWithName(string name);
        void GetBlocks(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyTerminalBlock> blocks);
        void GetBlocksOfType(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyTerminalBlock> blocks, System.Func`<Sandbox.ModAPI.Ingame.IMyTerminalBlock, bool> collect);
        void GetBlocksOfType(<> blocks, <, bool> collect);
        Sandbox.ModAPI.Ingame.IMyTerminalBlock GetBlockWithId(long id);
        Sandbox.ModAPI.Ingame.IMyTerminalBlock GetBlockWithName(string name);
        void SearchBlocksOfName(string name, System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyTerminalBlock> blocks, System.Func`<Sandbox.ModAPI.Ingame.IMyTerminalBlock, bool> collect);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyGyro
    {
        bool GyroOverride { get; set; }
        float GyroPower { get; set; }
        float Pitch { get; set; }
        float Roll { get; set; }
        float Yaw { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyIntergridCommunicationSystem
    {
        long Me { get; }
        Sandbox.ModAPI.Ingame.IMyUnicastListener UnicastListener { get; }
        void DisableBroadcastListener(Sandbox.ModAPI.Ingame.IMyBroadcastListener broadcastListener);
        void GetBroadcastListeners(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyBroadcastListener> broadcastListeners, System.Func`<Sandbox.ModAPI.Ingame.IMyBroadcastListener, bool> collect);
        bool IsEndpointReachable(long address, Sandbox.ModAPI.Ingame.TransmissionDistance transmissionDistance);
        Sandbox.ModAPI.Ingame.IMyBroadcastListener RegisterBroadcastListener(string tag);
        void SendBroadcastMessage(string tag,  data, Sandbox.ModAPI.Ingame.TransmissionDistance transmissionDistance);
        bool SendUnicastMessage(long addressee, string tag,  data);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyItemProducerComponent
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyJumpDrive
    {
        float CurrentStoredPower { get; }
        float JumpDistanceMeters { get; set; }
        float JumpDistanceRatio { get; set; }
        float MaxJumpDistanceMeters { get; }
        float MaxStoredPower { get; }
        float MinJumpDistanceMeters { get; }
        bool Recharge { get; set; }
        Sandbox.ModAPI.Ingame.MyJumpDriveStatus Status { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyLargeTurretBase
    {
        bool AIEnabled { get; }
        float Azimuth { get; set; }
        bool CanControl { get; }
        float Elevation { get; set; }
        bool EnableIdleRotation { get; set; }
        bool HasTarget { get; }
        bool IsAimed { get; }
        bool IsUnderControl { get; }
        float Range { get; set; }
        bool TargetCharacters { get; set; }
        bool TargetEnemies { get; set; }
        bool TargetLargeGrids { get; set; }
        bool TargetMeteors { get; set; }
        bool TargetMissiles { get; set; }
        bool TargetNeutrals { get; set; }
        bool TargetSmallGrids { get; set; }
        bool TargetStations { get; set; }
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo GetTargetedEntity();
        string GetTargetingGroup();
        void GetTargetingGroups(System.Collections.Generic.List`<string> targetingGroups);
        System.Collections.Generic.List`<string> GetTargetingGroups();
        void ResetTargetingToDefault();
        void SetManualAzimuthAndElevation(float azimuth, float elevation);
        void SetTarget(VRageMath.Vector3D pos);
        void SetTargetingGroup(string groupSubtypeId);
        void SyncAzimuth();
        void SyncElevation();
        void SyncEnableIdleRotation();
        void TrackTarget(VRageMath.Vector3D pos, VRageMath.Vector3 velocity);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyLaserAntenna
    {
        bool IsOutsideLimits { get; }
        bool IsPermanent { get; set; }
        float Range { get; set; }
        bool RequireLoS { get; }
        Sandbox.ModAPI.Ingame.MyLaserAntennaStatus Status { get; }
        VRageMath.Vector3D TargetCoords { get; }
        void Connect();
        void SetTargetCoords(string coords);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyLightingBlock
    {
        float BlinkIntervalSeconds { get; set; }
        float BlinkLenght { get; }
        float BlinkLength { get; set; }
        float BlinkOffset { get; set; }
        VRageMath.Color Color { get; set; }
        float Falloff { get; set; }
        float Intensity { get; set; }
        float Radius { get; set; }
        float ReflectorRadius { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyLightingComponent
    {
        float BlinkIntervalSeconds { get; set; }
        float BlinkLength { get; set; }
        float BlinkOffset { get; set; }
        VRageMath.Color Color { get; set; }
        float Falloff { get; set; }
        float Intensity { get; set; }
        float Radius { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMechanicalConnectionBlock
    {
        bool IsAttached { get; }
        bool IsLocked { get; }
        bool PendingAttachment { get; }
        bool SafetyLock { get; set; }
        float SafetyLockSpeed { get; set; }
        Sandbox.ModAPI.Ingame.IMyAttachableTopBlock Top { get; }
        VRage.Game.ModAPI.Ingame.IMyCubeGrid TopGrid { get; }
        void Attach();
        void Detach();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMessageProvider
    {
        bool HasPendingMessage { get; }
        int MaxWaitingMessages { get; }
        Sandbox.ModAPI.Ingame.MyIGCMessage AcceptMessage();
        void DisableMessageCallback();
        void SetMessageCallback(string argument);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorAdvancedRotor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorAdvancedStator
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorBase
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorRotor
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorStator
    {
        float Angle { get; }
        float BrakingTorque { get; set; }
        float Displacement { get; set; }
        float LowerLimitDeg { get; set; }
        float LowerLimitRad { get; set; }
        bool RotorLock { get; set; }
        float TargetVelocityRad { get; set; }
        float TargetVelocityRPM { get; set; }
        float Torque { get; set; }
        float UpperLimitDeg { get; set; }
        float UpperLimitRad { get; set; }
        void RotateToAngle(Sandbox.ModAPI.Ingame.MyRotationDirection dir, float desiredAng, float velAbsRpm);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyMotorSuspension
    {
        bool AirShockEnabled { get; set; }
        bool Brake { get; set; }
        float Damping { get; }
        float Friction { get; set; }
        float Height { get; set; }
        bool InvertPropulsion { get; set; }
        bool InvertSteer { get; set; }
        bool IsParkingEnabled { get; set; }
        float MaxSteerAngle { get; set; }
        float Power { get; set; }
        bool Propulsion { get; set; }
        float PropulsionOverride { get; set; }
        float SteerAngle { get; }
        bool Steering { get; set; }
        float SteeringOverride { get; set; }
        float SteerReturnSpeed { get; }
        float SteerSpeed { get; }
        float Strength { get; set; }
        float SuspensionTravel { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOffensiveCombatBlock
    {
        int LastScan { get; }
        Sandbox.ModAPI.Ingame.IMySearchEnemyComponent SearchEnemyComponent { get; }
        long SelectedAttackPattern { get; set; }
        VRage.Game.ModAPI.Ingame.OffensiveCombatTargetPriority TargetPriority { get; set; }
        int UpdateTargetInterval { get; set; }
         GetAttackPatternIds( idsList);
        bool TryGetSelectedAttackPattern(Sandbox.ModAPI.Ingame.IMyAttackPatternComponent attackPatternComponent);
        bool TryGetSelectedAttackPattern(long patternId, Sandbox.ModAPI.Ingame.IMyAttackPatternComponent attackPatternComponent);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOffensiveCombatCircleOrbit
    {
        float CircleDistance { get; set; }
        bool CircleInPGravity { get; set; }
        VRageMath.Base6Directions.DirectionFlags Facing { get; set; }
        bool IsOrbiting { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOffensiveCombatHitAndRun
    {
        float BreakOffDistance { get; set; }
        bool IsMovingAwayFromTarget { get; }
        bool IsMovingToTarget { get; }
        float RetreatAngle { get; set; }
        float RetreatDistance { get; set; }
        float RetreatTimeout { get; set; }
        void GetSelectedWeapons(System.Collections.Generic.List`<long> blockEntityIds);
        bool IsWeaponSelected(long blockEntityId);
        void SetSelectedWeapons(System.Collections.Generic.List`<long> blockEntityId);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOffensiveCombatIntercept
    {
        VRage.Game.ModAPI.Ingame.GuidanceType GuidanceType { get; set; }
        bool ShouldOverrideCollisionAvoidance { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOffensiveCombatStayAtRange
    {
        float EvasiveManeuverDistance { get; }
        bool EvasiveManeuvers { get; set; }
        VRageMath.Base6Directions.DirectionFlags FacingPriority { get; set; }
        float MaximalDistance { get; set; }
        float MinimalDistance { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyOreDetector
    {
        bool BroadcastUsingAntennas { get; set; }
        float Range { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPassage
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPathRecorderBlock
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPathRecorderComponent
    {
        string BeaconDisplayText { get; }
        System.Nullable`<long> BeaconEntityId { get; }
        VRageMath.Vector3D BeaconWorldPosition { get; }
        bool IsPlaying { get; }
        bool IsRecording { get; }
        float MinimalDistance { get; set; }
        System.Byte RecordInterval { get; set; }
        bool RepeatPath { get; set; }
        bool ShowPath { get; set; }
        bool ShowSelectedPoints { get; set; }
        void Play();
        void Record();
        void RemoveBeacon();
        void StopPlay();
        void StopRecord();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPistonBase
    {
        float CurrentPosition { get; }
        float HighestPosition { get; }
        float LowestPosition { get; }
        float MaxLimit { get; set; }
        float MaxVelocity { get; }
        float MinLimit { get; set; }
        float NormalizedPosition { get; }
        Sandbox.ModAPI.Ingame.PistonStatus Status { get; }
        float Velocity { get; set; }
        void Extend();
        void MoveToPosition(float extent, float speed);
        void Retract();
        void Reverse();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPistonTop
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyPowerProducer
    {
        float CurrentOutput { get; }
        float CurrentOutputRatio { get; }
        float MaxOutput { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyProductionBlock
    {
        VRage.Game.ModAPI.Ingame.IMyInventory InputInventory { get; }
        bool IsProducing { get; }
        bool IsQueueEmpty { get; }
        System.UInt32 NextItemId { get; }
        VRage.Game.ModAPI.Ingame.IMyInventory OutputInventory { get; }
        bool UseConveyorSystem { get; set; }
        void AddQueueItem(VRage.Game.MyDefinitionId blueprint, VRage.MyFixedPoint amount);
        void AddQueueItem(VRage.Game.MyDefinitionId blueprint, double amount);
        void AddQueueItem(VRage.Game.MyDefinitionId blueprint, System.Decimal amount);
        bool CanUseBlueprint(VRage.Game.MyDefinitionId blueprint);
        void ClearQueue();
        void GetQueue(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyProductionItem> items);
        void InsertQueueItem(int idx, VRage.Game.MyDefinitionId blueprint, double amount);
        void InsertQueueItem(int idx, VRage.Game.MyDefinitionId blueprint, VRage.MyFixedPoint amount);
        void InsertQueueItem(int idx, VRage.Game.MyDefinitionId blueprint, System.Decimal amount);
        void MoveQueueItemRequest(System.UInt32 queueItemId, int targetIdx);
        void RemoveQueueItem(int idx, System.Decimal amount);
        void RemoveQueueItem(int idx, VRage.MyFixedPoint amount);
        void RemoveQueueItem(int idx, double amount);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyProgrammableBlock
    {
        bool IsRunning { get; }
        string TerminalRunArgument { get; }
        bool TryRun(string argument);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyProjector
    {
        int BuildableBlocksCount { get; }
        bool IsProjecting { get; }
        VRageMath.Vector3I ProjectionOffset { get; set; }
        int ProjectionOffsetX { get; }
        int ProjectionOffsetY { get; }
        int ProjectionOffsetZ { get; }
        VRageMath.Vector3I ProjectionRotation { get; set; }
        int ProjectionRotX { get; }
        int ProjectionRotY { get; }
        int ProjectionRotZ { get; }
        int RemainingArmorBlocks { get; }
        int RemainingBlocks { get; }
        System.Collections.Generic.Dictionary`<VRage.Game.MyDefinitionBase, int> RemainingBlocksPerType { get; }
        bool ShowOnlyBuildable { get; set; }
        int TotalBlocks { get; }
        void UpdateOffsetAndRotation();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyRadioAntenna
    {
        bool EnableBroadcasting { get; set; }
        string HudText { get; set; }
        bool IsBroadcasting { get; }
        float Radius { get; set; }
        bool ShowShipName { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyReactor
    {
        bool UseConveyorSystem { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyRefinery
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyReflectorLight
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyRemoteControl
    {
        Sandbox.ModAPI.Ingame.MyWaypointInfo CurrentWaypoint { get; }
        VRageMath.Base6Directions.Direction Direction { get; set; }
        Sandbox.ModAPI.Ingame.FlightMode FlightMode { get; set; }
        bool IsAutoPilotEnabled { get; }
        float SpeedLimit { get; set; }
        bool WaitForFreeWay { get; set; }
        void AddWaypoint(Sandbox.ModAPI.Ingame.MyWaypointInfo coords);
        void AddWaypoint(VRageMath.Vector3D coords, string name);
        void ClearWaypoints();
        bool GetNearestPlayer(VRageMath.Vector3D playerPosition);
        void GetWaypointInfo(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyWaypointInfo> waypoints);
        void SetAutoPilotEnabled(bool enabled);
        void SetCollisionAvoidance(bool enabled);
        void SetDockingMode(bool enabled);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyResourceStorageComponent
    {
        double FilledRatio { get; }
        float ResourceCapacity { get; }
        bool IsResourceStorage(VRage.Game.MyDefinitionId resourceDefinition);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySearchEnemyComponent
    {
        System.Nullable`<long> FoundEnemyId { get; }
        VRage.Utils.MyStringHash SubsystemsToDestroy { get; set; }
        VRage.Game.ModAPI.Ingame.MyGridTargetingRelationFiltering TargetingLockOptions { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySearchlight
    {
        float AimingRadius { get; set; }
        float BlinkInterval { get; set; }
        float BlinkLength { get; set; }
        float BlinkOffset { get; set; }
        VRageMath.Color Color { get; set; }
        bool EnableIdleMovement { get; set; }
        float Intensity { get; set; }
        float Offset { get; set; }
        float Radius { get; set; }
        bool TargetCharacters { get; set; }
        bool TargetEnemy { get; set; }
        bool TargetFriends { get; set; }
        bool TargetLargeShips { get; set; }
        bool TargetLockEnemy { get; set; }
        bool TargetMeteors { get; set; }
        bool TargetNeutrals { get; set; }
        Sandbox.ModAPI.Ingame.TargetingGroupOptions TargetOptions { get; }
        bool TargetRockets { get; set; }
        bool TargetSmallShips { get; set; }
        bool TargetStations { get; set; }
        void SetManualAzimuthAndElevation(float azimuth, float elevation);
        void SetTargetOptions(Sandbox.ModAPI.Ingame.TargetingGroupOptions Options);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySensorBlock
    {
        float BackExtend { get; set; }
        float BottomExtend { get; set; }
        bool DetectAsteroids { get; set; }
        bool DetectEnemy { get; set; }
        bool DetectFloatingObjects { get; set; }
        bool DetectFriendly { get; set; }
        bool DetectLargeShips { get; set; }
        bool DetectNeutral { get; set; }
        bool DetectOwner { get; set; }
        bool DetectPlayers { get; set; }
        bool DetectSmallShips { get; set; }
        bool DetectStations { get; set; }
        bool DetectSubgrids { get; set; }
        float FrontExtend { get; set; }
        bool IsActive { get; }
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo LastDetectedEntity { get; }
        float LeftExtend { get; set; }
        float MaxRange { get; }
        bool PlayProximitySound { get; set; }
        float RightExtend { get; set; }
        float TopExtend { get; set; }
        void DetectedEntities(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyDetectedEntityInfo> entities);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipConnector
    {
        bool CollectAll { get; set; }
        bool IsConnected { get; }
        bool IsLocked { get; }
        bool IsParkingEnabled { get; set; }
        Sandbox.ModAPI.Ingame.IMyShipConnector OtherConnector { get; }
        float PullStrength { get; set; }
        Sandbox.ModAPI.Ingame.MyShipConnectorStatus Status { get; }
        bool ThrowOut { get; set; }
        void Connect();
        void Disconnect();
        void ToggleConnect();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipController
    {
        bool CanControlShip { get; }
        VRageMath.Vector3D CenterOfMass { get; }
        bool ControlThrusters { get; set; }
        bool ControlWheels { get; set; }
        bool DampenersOverride { get; set; }
        bool HandBrake { get; set; }
        bool HasWheels { get; }
        bool IsMainCockpit { get; set; }
        bool IsUnderControl { get; }
        VRageMath.Vector3 MoveIndicator { get; }
        float RollIndicator { get; }
        VRageMath.Vector2 RotationIndicator { get; }
        bool ShowHorizonIndicator { get; set; }
        Sandbox.ModAPI.Ingame.MyShipMass CalculateShipMass();
        VRageMath.Vector3D GetArtificialGravity();
        VRageMath.Vector3D GetNaturalGravity();
        double GetShipSpeed();
        Sandbox.ModAPI.Ingame.MyShipVelocities GetShipVelocities();
        VRageMath.Vector3D GetTotalGravity();
        bool TryGetPlanetElevation(Sandbox.ModAPI.Ingame.MyPlanetElevation detail, double elevation);
        bool TryGetPlanetPosition(VRageMath.Vector3D position);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipDrill
    {
        bool TerrainClearingMode { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipGrinder
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipToolBase
    {
        bool IsActivated { get; }
        bool UseConveyorSystem { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyShipWelder
    {
        bool HelpOthers { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySmallGatlingGun
    {
        bool UseConveyorSystem { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySmallMissileLauncher
    {
        bool UseConveyorSystem { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySmallMissileLauncherReload
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySolarFoodGenerator
    {
        float ItemsPerMinute { get; }
        float TimeRemainingUntilNextBatch { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMySolarOccludable
    {
        bool IsSolarOccluded { get; }
        long GetEntityId();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyStoreBlock
    {
        bool Searchable { get; set; }
        bool CancelStoreItem(long id);
        void GetPlayerStoreItems(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.MyStoreQueryItem> storeItems);
        Sandbox.ModAPI.Ingame.MyStoreInsertResults InsertOffer(VRage.Game.ModAPI.Ingame.MyStoreItemDataSimple item, long id);
        Sandbox.ModAPI.Ingame.MyStoreInsertResults InsertOrder(VRage.Game.ModAPI.Ingame.MyStoreItemDataSimple item, long id);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyTargetDummyBlock
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyTerminalBlock
    {
        string CustomData { get; set; }
        string CustomInfo { get; }
        string CustomName { get; set; }
        string CustomNameWithFaction { get; }
        string DetailedInfo { get; }
        bool ShowInInventory { get; set; }
        bool ShowInTerminal { get; set; }
        bool ShowInToolbarConfig { get; set; }
        bool ShowOnHUD { get; set; }
        void GetActions(System.Collections.Generic.List`<Sandbox.ModAPI.Interfaces.ITerminalAction> resultList, System.Func`<Sandbox.ModAPI.Interfaces.ITerminalAction, bool> collect);
        Sandbox.ModAPI.Interfaces.ITerminalAction GetActionWithName(string name);
        void GetProperties(System.Collections.Generic.List`<Sandbox.ModAPI.Interfaces.ITerminalProperty> resultList, System.Func`<Sandbox.ModAPI.Interfaces.ITerminalProperty, bool> collect);
        Sandbox.ModAPI.Interfaces.ITerminalProperty GetProperty(string id);
        bool HasLocalPlayerAccess();
        bool HasNobodyPlayerAccessToBlock();
        bool HasPlayerAccess(long playerId, VRage.Game.MyRelationsBetweenPlayerAndBlock defaultNoUser);
        bool HasPlayerAccessWithNobodyCheck(long playerId, bool isForPB);
        bool IsSameConstructAs(Sandbox.ModAPI.Ingame.IMyTerminalBlock other);
        void SearchActionsOfName(string name, System.Collections.Generic.List`<Sandbox.ModAPI.Interfaces.ITerminalAction> resultList, System.Func`<Sandbox.ModAPI.Interfaces.ITerminalAction, bool> collect);
        void SetCustomName(System.Text.StringBuilder text);
        void SetCustomName(string text);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyTextPanel
    {
        string GetPublicTitle();
        bool WritePublicTitle(string value, bool append);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyTextSurface
    {
        VRage.Game.GUI.TextPanel.TextAlignment Alignment { get; set; }
        System.Byte BackgroundAlpha { get; set; }
        VRageMath.Color BackgroundColor { get; set; }
        float ChangeInterval { get; set; }
        VRage.Game.GUI.TextPanel.ContentType ContentType { get; set; }
        string CurrentlyShownImage { get; }
        string DisplayName { get; }
        string Font { get; set; }
        VRageMath.Color FontColor { get; set; }
        float FontSize { get; set; }
        string Name { get; }
        bool PreserveAspectRatio { get; set; }
        string Script { get; set; }
        VRageMath.Color ScriptBackgroundColor { get; set; }
        VRageMath.Color ScriptForegroundColor { get; set; }
        VRageMath.Vector2 SurfaceSize { get; }
        float TextPadding { get; set; }
        VRageMath.Vector2 TextureSize { get; }
        void AddImagesToSelection(System.Collections.Generic.List`<string> ids, bool checkExistence);
        void AddImageToSelection(string id, bool checkExistence);
        void ClearImagesFromSelection();
        VRage.Game.GUI.TextPanel.MySpriteDrawFrame DrawFrame();
        void GetFonts(System.Collections.Generic.List`<string> fonts);
        void GetScripts(System.Collections.Generic.List`<string> scripts);
        void GetSelectedImages(System.Collections.Generic.List`<string> output);
        void GetSprites(System.Collections.Generic.List`<string> sprites);
        string GetText();
        VRageMath.Vector2 MeasureStringInPixels(System.Text.StringBuilder text, string font, float scale);
        void ReadText(System.Text.StringBuilder buffer, bool append);
        void RemoveImageFromSelection(string id, bool removeDuplicates);
        void RemoveImagesFromSelection(System.Collections.Generic.List`<string> ids, bool removeDuplicates);
        bool WriteText(string value, bool append);
        bool WriteText(System.Text.StringBuilder value, bool append);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyTextSurfaceProvider
    {
        int SurfaceCount { get; }
        bool UseGenericLcd { get; }
        Sandbox.ModAPI.Ingame.IMyTextSurface GetSurface(int index);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyThrust
    {
        float CurrentThrust { get; }
        float CurrentThrustPercentage { get; }
        VRageMath.Vector3I GridThrustDirection { get; }
        float MaxEffectiveThrust { get; }
        float MaxThrust { get; }
        float ThrustOverride { get; set; }
        float ThrustOverridePercentage { get; set; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyUnicastListener
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyUpgradableBlock
    {
        System.UInt32 UpgradeCount { get; }
        void FillUpgradesDictionary(System.Collections.Generic.Dictionary`<string, float> upgrades);
        void GetUpgrades(System.Collections.Generic.Dictionary`<string, float> upgrades);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyUpgradeModule
    {
        System.UInt32 Connections { get; }
        System.UInt32 UpgradeCount { get; }
        void FillUpgradeList(System.Collections.Generic.List`<VRage.Game.ObjectBuilders.Definitions.MyUpgradeModuleInfo> upgrades);
        void GetUpgradeList(System.Collections.Generic.List`<VRage.Game.ObjectBuilders.Definitions.MyUpgradeModuleInfo> upgrades);
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyUserControllableGun
    {
        bool IsShooting { get; }
        bool Shoot { get; set; }
        void ShootOnce();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyWarhead
    {
        float DetonationTime { get; set; }
        bool IsArmed { get; set; }
        bool IsCountingDown { get; }
        void Detonate();
        bool StartCountdown();
        bool StopCountdown();
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyWheel
    {
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public interface IMyWindTurbine
    {
        float Effectivity { get; }
        float PlacementEffectivity { get; }
        float WindEffectivity { get; }
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyAssemblerMode
    {
        Assembly,
        Disassembly
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyConveyorSorterMode
    {
        Whitelist,
        Blacklist
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyDetectedEntityType
    {
        None,
        Unknown,
        SmallGrid,
        LargeGrid,
        CharacterHuman,
        CharacterOther,
        FloatingObject,
        Asteroid,
        Planet,
        Meteor,
        Missile,
        Tree,
        Forageable
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyJumpDriveStatus
    {
        Charging,
        Ready,
        Jumping
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyLaserAntennaStatus
    {
        Idle,
        RotatingToTarget,
        SearchingTargetForAntenna,
        Connecting,
        Connected,
        OutOfRange
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyPlanetElevation
    {
        Sealevel,
        Surface
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyRotationDirection
    {
        AUTO,
        CW,
        CCW
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyShipConnectorStatus
    {
        Unconnected,
        Connectable,
        Connected
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyStoreInsertResults
    {
        Success,
        Fail_StoreLimitReached,
        Fail_PricePerUnitIsLessThanMinimum,
        Error
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyTerminalAccessScope
    {
        All,
        Construct,
        Grid
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum MyTransmitTarget
    {
        None,
        Owned,
        Ally,
        Default,
        Neutral,
        Enemy,
        Everyone
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum PistonStatus
    {
        Stopped,
        Extending,
        Extended,
        Retracting,
        Retracted
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum TargetingGroupOptions
    {
        Default,
        Weapons,
        Propulsion,
        Power
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum TransmissionDistance
    {
        CurrentConstruct,
        ConnectedConstructs,
        AntennaRelay,
        TransmissionDistanceMax
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum UpdateFrequency
    {
        None,
        Update1,
        Update10,
        Update100,
        Once
    }
}
namespace Sandbox.ModAPI.Ingame
{
    public enum UpdateType
    {
        None,
        Terminal,
        Trigger,
        Mod,
        Script,
        Update1,
        Update10,
        Update100,
        Once,
        IGC
    }
}
namespace SpaceEngineers.Game.ModAPI.Ingame
{
    public interface IMyTurretControlBlock
    {
        bool AIEnabled { get; set; }
        float AngleDeviation { get; set; }
        Sandbox.ModAPI.Ingame.IMyMotorStator AzimuthRotor { get; set; }
        Sandbox.ModAPI.Ingame.IMyCameraBlock Camera { get; set; }
        Sandbox.ModAPI.Ingame.IMyMotorStator ElevationRotor { get; set; }
        bool HasTarget { get; }
        bool IsAimed { get; }
        bool IsSunTrackerEnabled { get; set; }
        bool IsUnderControl { get; }
        VRageMath.Vector3 MoveIndicator { get; }
        float Range { get; set; }
        float RollIndicator { get; }
        VRageMath.Vector2 RotationIndicator { get; }
        bool TargetCharacters { get; set; }
        bool TargetFriends { get; set; }
        bool TargetLargeGrids { get; set; }
        bool TargetMeteors { get; set; }
        bool TargetMissiles { get; set; }
        bool TargetNeutrals { get; set; }
        bool TargetSmallGrids { get; set; }
        bool TargetStations { get; set; }
        float VelocityMultiplierAzimuthRpm { get; set; }
        float VelocityMultiplierElevationRpm { get; set; }
        void AddTool(Sandbox.ModAPI.Ingame.IMyFunctionalBlock tool);
        void AddTools(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyFunctionalBlock> tools);
        void ClearTools();
        Sandbox.ModAPI.Ingame.IMyTerminalBlock GetDirectionSource();
        VRageMath.Vector3 GetShootDirection();
        Sandbox.ModAPI.Ingame.MyDetectedEntityInfo GetTargetedEntity();
        string GetTargetingGroup();
        System.Collections.Generic.List`<string> GetTargetingGroups();
        void GetTargetingGroups(System.Collections.Generic.List`<string> targetingGroups);
        void GetTools(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyFunctionalBlock> tools);
        void RemoveTool(Sandbox.ModAPI.Ingame.IMyFunctionalBlock tool);
        void RemoveTools(System.Collections.Generic.List`<Sandbox.ModAPI.Ingame.IMyFunctionalBlock> tool);
        void SetTargetingGroup(string groupSubtypeId);
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum FleeMode
    {
        AwayFromTarget,
        ToGpsOrBeacon
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum FleeTrigger
    {
        Never,
        Always,
        WhenTargetLocked,
        WhenTakingDamage
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum GuidanceType
    {
        Basic,
        TargetPrediction
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyCubeBlock
    {
        VRage.ObjectBuilders.SerializableDefinitionId BlockDefinition { get; }
        VRage.Game.ModAPI.Ingame.IMyCubeGrid CubeGrid { get; }
        string DefinitionDisplayNameText { get; }
        float DisassembleRatio { get; }
        string DisplayNameText { get; }
        bool IsBeingHacked { get; }
        bool IsFunctional { get; }
        bool IsWorking { get; }
        float Mass { get; }
        VRageMath.Vector3I Max { get; }
        VRageMath.Vector3I Min { get; }
        int NumberInGrid { get; }
        VRageMath.MyBlockOrientation Orientation { get; }
        long OwnerId { get; }
        VRageMath.Vector3I Position { get; }
        string GetOwnerFactionTag();
        VRage.Game.MyRelationsBetweenPlayerAndBlock GetPlayerRelationToOwner();
        VRage.Game.MyRelationsBetweenPlayerAndBlock GetUserRelationToOwner(long playerId, VRage.Game.MyRelationsBetweenPlayerAndBlock defaultNoUser);
        void UpdateIsWorking();
        void UpdateVisual();
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyCubeGrid
    {
        string CustomName { get; set; }
        float GridSize { get; }
        VRage.Game.MyCubeSize GridSizeEnum { get; }
        bool IsStatic { get; }
        VRageMath.Vector3 LinearVelocity { get; }
        VRageMath.Vector3I Max { get; }
        VRageMath.Vector3I Min { get; }
        float Speed { get; }
        bool CubeExists(VRageMath.Vector3I pos);
        VRage.Game.ModAPI.Ingame.IMySlimBlock GetCubeBlock(VRageMath.Vector3I pos);
        VRageMath.Vector3D GridIntegerToWorld(VRageMath.Vector3I gridCoords);
        bool IsSameConstructAs(VRage.Game.ModAPI.Ingame.IMyCubeGrid other);
        VRageMath.Vector3I WorldToGridInteger(VRageMath.Vector3D coords);
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyEntity
    {
        bool Closed { get; }
        VRage.Game.Components.Interfaces.IMyEntityComponentContainer Components { get; }
        string DisplayName { get; }
        long EntityId { get; }
        bool HasInventory { get; }
        int InventoryCount { get; }
        string Name { get; }
        VRageMath.BoundingBoxD WorldAABB { get; }
        VRageMath.BoundingBoxD WorldAABBHr { get; }
        VRageMath.MatrixD WorldMatrix { get; }
        VRageMath.BoundingSphereD WorldVolume { get; }
        VRageMath.BoundingSphereD WorldVolumeHr { get; }
        VRage.Game.ModAPI.Ingame.IMyInventory GetInventory(int index);
        VRage.Game.ModAPI.Ingame.IMyInventory GetInventory();
        VRageMath.Vector3D GetPosition();
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyInventory
    {
        bool CanPutItems { get; }
        VRage.MyFixedPoint CurrentMass { get; }
        VRage.MyFixedPoint CurrentVolume { get; }
        bool IsFull { get; }
        int ItemCount { get; }
        VRage.MyFixedPoint MaxVolume { get; }
        VRage.Game.ModAPI.Ingame.IMyEntity Owner { get; }
        float VolumeFillFactor { get; }
        bool CanItemsBeAdded(VRage.MyFixedPoint amount, VRage.Game.ModAPI.Ingame.MyItemType itemType);
        bool CanTransferItemTo(VRage.Game.ModAPI.Ingame.IMyInventory otherInventory, VRage.Game.ModAPI.Ingame.MyItemType itemType);
        bool ContainItems(VRage.MyFixedPoint amount, VRage.Game.ModAPI.Ingame.MyItemType itemType);
        System.Nullable`<VRage.Game.ModAPI.Ingame.MyInventoryItem> FindItem(VRage.Game.ModAPI.Ingame.MyItemType itemType);
        void GetAcceptedItems(System.Collections.Generic.List`<VRage.Game.ModAPI.Ingame.MyItemType> itemsTypes, System.Func`<VRage.Game.ModAPI.Ingame.MyItemType, bool> filter);
        VRage.MyFixedPoint GetItemAmount(VRage.Game.ModAPI.Ingame.MyItemType itemType);
        System.Nullable`<VRage.Game.ModAPI.Ingame.MyInventoryItem> GetItemAt(int index);
        System.Nullable`<VRage.Game.ModAPI.Ingame.MyInventoryItem> GetItemByID(System.UInt32 id);
        void GetItems(System.Collections.Generic.List`<VRage.Game.ModAPI.Ingame.MyInventoryItem> items, System.Func`<VRage.Game.ModAPI.Ingame.MyInventoryItem, bool> filter);
        bool IsConnectedTo(VRage.Game.ModAPI.Ingame.IMyInventory otherInventory);
        bool IsItemAt(int position);
        bool TransferItemFrom(VRage.Game.ModAPI.Ingame.IMyInventory sourceInventory, int sourceItemIndex, System.Nullable`<int> targetItemIndex, System.Nullable`<bool> stackIfPossible, System.Nullable`<VRage.MyFixedPoint> amount);
        bool TransferItemFrom(VRage.Game.ModAPI.Ingame.IMyInventory sourceInventory, VRage.Game.ModAPI.Ingame.MyInventoryItem item, System.Nullable`<VRage.MyFixedPoint> amount);
        bool TransferItemTo(VRage.Game.ModAPI.Ingame.IMyInventory dstInventory, VRage.Game.ModAPI.Ingame.MyInventoryItem item, System.Nullable`<VRage.MyFixedPoint> amount);
        bool TransferItemTo(VRage.Game.ModAPI.Ingame.IMyInventory dst, int sourceItemIndex, System.Nullable`<int> targetItemIndex, System.Nullable`<bool> stackIfPossible, System.Nullable`<VRage.MyFixedPoint> amount);
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyInventoryItem
    {
        VRage.MyFixedPoint Amount { get; set; }
        VRage.ObjectBuilders.MyObjectBuilder_Base Content { get; set; }
        System.UInt32 ItemId { get; set; }
        float Scale { get; set; }
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMyInventoryOwner
    {
        long EntityId { get; }
        bool HasInventory { get; }
        int InventoryCount { get; }
        bool UseConveyorSystem { get; set; }
        VRage.Game.ModAPI.Ingame.IMyInventory GetInventory(int index);
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public interface IMySlimBlock
    {
        float AccumulatedDamage { get; }
        VRage.ObjectBuilders.SerializableDefinitionId BlockDefinition { get; }
        float BuildIntegrity { get; }
        float BuildLevelRatio { get; }
        VRageMath.Vector3 ColorMaskHSV { get; }
        VRage.Game.ModAPI.Ingame.IMyCubeGrid CubeGrid { get; }
        float CurrentDamage { get; }
        float DamageRatio { get; }
        VRage.Game.ModAPI.Ingame.IMyCubeBlock FatBlock { get; }
        bool HasDeformation { get; }
        bool IsDestroyed { get; }
        bool IsFullIntegrity { get; }
        bool IsFullyDismounted { get; }
        float Mass { get; }
        float MaxDeformation { get; }
        float MaxIntegrity { get; }
        long OwnerId { get; }
        VRageMath.Vector3I Position { get; }
        bool ShowParts { get; }
        VRage.Utils.MyStringHash SkinSubtypeId { get; }
        bool StockpileAllocated { get; }
        bool StockpileEmpty { get; }
        void GetMissingComponents(System.Collections.Generic.Dictionary`<string, int> addToDictionary);
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum MyGridTargetingRelationFiltering
    {
        None,
        Enemy,
        Neutral,
        Friend,
        All
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum MyTransponderRelationFilter
    {
        Owner,
        Faction,
        Everyone
    }
}
namespace VRage.Game.ModAPI.Ingame
{
    public enum OffensiveCombatTargetPriority
    {
        Closest,
        Largest,
        Smallest
    }
}
