param(
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [string]$SpaceEngineersBin64 = "C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64",
    [string]$OutputSource = "data\se_api_surface_source.cs"
)

$ErrorActionPreference = "Stop"

$bin64 = [System.IO.Path]::GetFullPath($SpaceEngineersBin64)
if (-not (Test-Path -LiteralPath $bin64)) {
    throw "Space Engineers Bin64 folder not found: $bin64"
}

$output = if ([System.IO.Path]::IsPathRooted($OutputSource)) {
    $OutputSource
}
else {
    Join-Path $ProjectRoot $OutputSource
}
$output = [System.IO.Path]::GetFullPath($output)
New-Item -ItemType Directory -Force -Path ([System.IO.Path]::GetDirectoryName($output)) | Out-Null

$assemblyCache = @{}
[System.AppDomain]::CurrentDomain.add_AssemblyResolve({
    param($sender, $eventArgs)
    $name = (New-Object System.Reflection.AssemblyName($eventArgs.Name)).Name + ".dll"
    $candidate = Join-Path $bin64 $name
    if (Test-Path -LiteralPath $candidate) {
        return [System.Reflection.Assembly]::LoadFrom($candidate)
    }
    return $null
})

function Load-AssemblySafe([string]$path) {
    try {
        $full = [System.IO.Path]::GetFullPath($path)
        if (-not $assemblyCache.ContainsKey($full)) {
            $assemblyCache[$full] = [System.Reflection.Assembly]::LoadFrom($full)
        }
        return $assemblyCache[$full]
    }
    catch {
        return $null
    }
}

function Get-TypesSafe($assembly) {
    try {
        return $assembly.GetExportedTypes()
    }
    catch [System.Reflection.ReflectionTypeLoadException] {
        return $_.Exception.Types | Where-Object { $_ -ne $null }
    }
    catch {
        return @()
    }
}

function Format-TypeName($type) {
    if ($null -eq $type) { return "object" }
    if ($type.IsByRef) { return Format-TypeName $type.GetElementType() }
    if ($type.IsArray) { return "$(Format-TypeName $type.GetElementType())[]" }
    if ($type.FullName -eq "System.Void") { return "void" }
    if ($type.FullName -eq "System.String") { return "string" }
    if ($type.FullName -eq "System.Boolean") { return "bool" }
    if ($type.FullName -eq "System.Int32") { return "int" }
    if ($type.FullName -eq "System.Int64") { return "long" }
    if ($type.FullName -eq "System.Single") { return "float" }
    if ($type.FullName -eq "System.Double") { return "double" }
    if (-not $type.IsGenericType) { return ($type.FullName -replace "\+", ".") }
    $base = ($type.FullName -replace "\+", ".") -replace "`\d+.*$", ""
    $args = ($type.GetGenericArguments() | ForEach-Object { Format-TypeName $_ }) -join ", "
    return "$base<$args>"
}

$assemblies = @(
    "VRage.dll",
    "VRage.Game.dll",
    "Sandbox.Common.dll",
    "Sandbox.Game.dll"
) | ForEach-Object { Join-Path $bin64 $_ } | ForEach-Object { Load-AssemblySafe $_ } | Where-Object { $_ -ne $null }

$types = foreach ($assembly in $assemblies) {
    Get-TypesSafe $assembly
}

$apiTypes = $types |
    Where-Object {
        $_.Namespace -and
        $_.Namespace.Contains(".Ingame") -and
        (($_.IsInterface -and $_.Name.StartsWith("IMy")) -or $_.IsEnum)
    } |
    Sort-Object FullName -Unique

$writer = New-Object System.IO.StreamWriter($output, $false, [System.Text.UTF8Encoding]::new($false))
try {
    $writer.WriteLine("// Generated by tools\probe_se_api_surface.ps1")
    $writer.WriteLine("// Source Bin64: $bin64")
    foreach ($type in $apiTypes) {
        $writer.WriteLine("namespace $($type.Namespace)")
        $writer.WriteLine("{")
        if ($type.IsEnum) {
            $writer.WriteLine("    public enum $($type.Name)")
            $writer.WriteLine("    {")
            $names = [System.Enum]::GetNames($type)
            for ($i = 0; $i -lt $names.Length; $i++) {
                $comma = if ($i -lt $names.Length - 1) { "," } else { "" }
                $writer.WriteLine("        $($names[$i])$comma")
            }
            $writer.WriteLine("    }")
        }
        elseif ($type.IsInterface) {
            $writer.WriteLine("    public interface $($type.Name)")
            $writer.WriteLine("    {")
            foreach ($property in ($type.GetProperties() | Sort-Object Name)) {
                $setter = if ($property.CanWrite) { " set;" } else { "" }
                $writer.WriteLine("        $(Format-TypeName $property.PropertyType) $($property.Name) { get;$setter }")
            }
            foreach ($method in ($type.GetMethods() | Where-Object { -not $_.IsSpecialName } | Sort-Object Name)) {
                $params = ($method.GetParameters() | ForEach-Object { "$(Format-TypeName $_.ParameterType) $($_.Name)" }) -join ", "
                $writer.WriteLine("        $(Format-TypeName $method.ReturnType) $($method.Name)($params);")
            }
            $writer.WriteLine("    }")
        }
        $writer.WriteLine("}")
    }
}
finally {
    $writer.Dispose()
}

Write-Host "Wrote $output with $($apiTypes.Count) API type declarations"
